export const hobbies = [
    'Archery',
    'Axe throwing',
    'BASE jumping',
    'Beauty pageants',
    'Birdwatching',
    'Book collecting',
    'Boxing',
    'Canoeing',
    'Caving',
    'Computer programming',
    'Die-cast toy',
    'Dolls',
    'Equestrianism',
    'Experimenting',
    'Fashion',
    'Flying disc',
    'Genealogy',
    'Glassblowing',
    'Gymnastics',
    'Ice hockey',
    'Jigsaw puzzles',
    'Jujitsu',
    'Kendama',
    'Knitting',
    'Kombucha brewing',
    'Lego building',
    'Letterboxing',
    'Marbles',
    'Mountaineering',
    'Paintball',
    'Phillumeny',
    'Playing musical instruments',
    'Pressed flower craft',
    'Quizzes',
    'Radio-controlled car racing',
    'Record collecting',
    'Running',
    'Shooting',
    'Shortwave listening',
    'Slacklining',
    'Soapmaking',
    'Stone skipping',
    'Sun bathing',
    'Trainspotting',
    'Vegetable farming',
    'Video game collecting',
    'Whale watching',
    'Woodworking',
    'Worldbuilding',
    'Wrestling',
];